name: Manual approval

permissions:
  issues: write

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Skip approval if not needed
        if: ${{ !(inputs.VERSION != '' && inputs.VERSION != '0.0.0' && endsWith(inputs.VERSION, '.0.0') ) }}
        run: echo "No approval needed"

      - name: Wait for manual approval
        # run only if a new version is detected and it is not a major version
        if: ${{ inputs.VERSION != '' && inputs.VERSION != '0.0.0' && endsWith(inputs.VERSION, '.0.0') }}
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: nileger, Moritz010902
          issue-title: "Manual approval neccessary for deployment"
          issue-body: "Please make sure that this repository is compatible with all the other services before procceeding."
          exclude-workflow-initiator-as-approver: false
