name: CI Pipeline

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  linting:
    uses: woped/devops/.github/workflows/linting.yaml@main
  test_maven:
    uses: woped/devops/.github/workflows/test_maven.yaml@main