name: Validate Commit Messages

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout commitlint config
        uses: actions/checkout@v4
        with:
          repository: woped/devops
          path: commitlint-config
          ref: main

      - name: Copy commitlint config
        run: cp commitlint-config/commitlint.config.js ./

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional

      - name: Validate current commit (last commit)
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose